knp_snappy:
    pdf:
        enabled:    true
        # ვიყენებთ კონკრეტულ მისამართს Docker კონტეინერის შიგნით
        binary:     '/usr/local/bin/wkhtmltopdf'
        options:    []
    image:
        enabled:    false # ჩვენ ამას არ ვიყენებთ
        # binary:     '/usr/local/bin/wkhtmltoimage'
        # options:    []
